### PR TITLE
Code Review for adding dynamically loaded DLL support

### PR DESCRIPTION
**Pull request by OswaldHurlem**
This is tested and works (on my machine, Windows 64-bit, not profiling GPU), but nonetheless this pull request is primarily so you can provide feedback on the design. I tried to make my changes as non-disruptive (to the design and performance) and rewindable as possible. The result is macro-heavy and somewhat messy.
I think it wouldn't be too harmful to turn the static variables into globals, and have their declarations be consolidated right at the same place as the MicroProfileGlobalState struct.
Renaming static depending on its context was just for me to find the globals more quickly, so that change can be blasted if you like.
The usage code could be simplified if I made it so that everything that is global is TLS. Or got rid of the TLS and used a hashtable to find logs. Again, I wanted to be non-disruptive.
Sorry about the # of commits.
Let me know what you think.

### CODE REVIEW

**Comment by xforce** [comment]
This seems to add support for statically linking microprofile into dlls and not break everything when doing that, or do I get this wrong?

I wanted to use microprofile too and here is what I did:
I just compiled microprofile as a dll, by just defining the MICROPROFILE_API on windows with either __declspec(dllexport) or __declspec(dllimport), and then linking the resulting .lib to all the dlls that use microprofile, that is a really easy way to get it to work with multiple dlls. I got this to work with like 10 lines of code. This is the patch I have for that, https://gist.github.com/xforce/2dc98e9b23bcf0e3da2971338f045d47

**Comment by jonasmr** [comment]
@xforce What you suggest is actually what MICROPROFILE_API is inteded for. However - instead of adding it directly in microprofile, you should make your own microprofile.config.h, and add it there.

**Comment by xforce** [comment]
@jonasmr ye true, I should probably change that.

**Comment by jonasmr** [comment]
closing, old

**Pull request closed without merging**
